### ISSUE TITLE
how to inject $app in the context?

### ISSUE THREAD

**Issue by Grummfy** [ciaranmcnulty/behat-psr7extension#14]
Hello,
how is it possible to inject the app from this extension inside a custom context?

I try this to get a factory or several other
```
      contexts:
        - FeatureContext:
            app: '@cjm.behat.psr7.factory.slim'
```

thanks

**Comment by ciaranmcnulty** [comment]
I suggest using https://github.com/Roave/behat-psr11extension  so we can keep this extension small and focussed
